require 'rake'
require 'rake/clean'
require 'rake/testtask'
require 'rake/rdoctask'

task(:default => :compile)

CLEAN.add ["ebb_ext.{o,bundle,so,obj,pdb,lib,def,exp}"]
CLOBBER.add ['Makefile', 'mkmf.log','doc', 'coverage']

desc 'compile the extension'
task(:compile => 'Makefile') { sh 'make' }
file('Makefile' => "ebb_ext.c") { ruby 'extconf.rb' }
